# Generated by Django 4.2.4 on 2023-10-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0005_delete_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(max_length=255)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("ticket", models.BooleanField(default=True)),
                ("desglosar", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientee",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "egreso",
                "verbose_name_plural": "egresos",
                "order_with_respect_to": "fecha_pedido",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("descripcion", models.CharField(max_length=255, unique=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos"),
                ),
                ("costo", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=20
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "order_with_respect_to": "descripcion",
            },
        ),
        migrations.CreateModel(
            name="ProductosEgreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("entregado", models.BooleanField(default=True)),
                ("devolucion", models.BooleanField(default=False)),
                (
                    "egreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.egreso",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto egreso",
                "verbose_name_plural": "productos egreso",
                "order_with_respect_to": "created",
            },
        ),
    ]
