# Generated by Django 4.2.4 on 2023-09-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="costo",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
