# Generated by Django 4.2.4 on 2023-09-22 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_producto_precio_alter_producto_costo"),
        ("clientes", "0002_rename_update_cliente_updated"),
    ]

    operations = []
