# Generated by Django 4.2.4 on 2023-10-05 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_merge_20230914_2122"),
        ("clientes", "0003_merge_20230922_0059"),
    ]

    operations = []
