# Generated by Django 4.2.4 on 2023-10-05 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0004_merge_20231004_2124"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
